name: trippo_driver
description: "trippo driver"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4

  # 이메일 주소 유효성검사 패키지 - https://pub.dev/packages/email_validator
  email_validator: ^3.0.0

  # 전화번호 필드 패키지 - https://pub.dev/packages/intl_phone_field
  intl_phone_field: ^3.2.0

  # 토스트문구표시 - https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.0.9

  # URL 이동 - https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.1

  # Google Maps - https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.11.0

  # 위치 정보 - https://pub.dev/packages/geolocator
  geolocator: ^10.1.0

  # geocoding? - https://pub.dev/packages/geocoder2
  geocoder2: ^1.3.0

  # flutter geofire -  https://pub.dev/packages/flutter_geofire
  flutter_geofire: ^2.0.4

  # flutter polyline points 경로그리기 - https://pub.dev/packages/flutter_polyline_points
  flutter_polyline_points: ^1.0.0

  # 현재 좌표 - https://pub.dev/packages/location
  location: ^5.0.0

  # 별점 평가 (스타수 적음) - https://pub.dev/packages/smooth_star_rating_nsafe
  smooth_star_rating_nsafe: 1.0.0+1

  # 흐르는 텍스트 ? - https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^4.2.2

  # http
  http: ^0.13.4

  # Provider - https://pub.dev/packages/provider/install
  provider: ^6.1.4

  # Audio Player - https://pub.dev/packages/assets_audio_player
  # assets_audio_player: ^3.0.2

  # UUID - https://pub.dev/packages/uuid
  # geolocator와 assets_audio_player 의존성충돌로 인해 설치명시
  # uuid: ^3.0.5

  googleapis_auth: ^1.4.1
  app_settings: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/2.0x/
    - images/3.0x/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
